export const examplesList = [
  {
    title: 'Simple',
    description: 'A simple map with an OSM source.',
    routerLink: 'simple',
    openLayersLink: 'https://openlayers.org/en/latest/examples/simple.html',
  },
  {
    title: 'Map position',
    description: 'Map longitude, latitude and zoom.',
    routerLink: 'map-position',
    openLayersLink: 'https://openlayers.org/en/latest/examples/center.html',
  },
  {
    title: 'Cursor position',
    description: 'Example of a mouse position control, outside the map.',
    routerLink: 'cursor-position',
    openLayersLink: 'https://openlayers.org/en/latest/examples/mouse-position.html',
  },
  {
    title: 'Display geometry',
    description:
      'Example of geojson features : point, polygon, linestring, circle, multi-point, multi-linestring, multi-polygon.',
    routerLink: 'display-geometry',
    openLayersLink: 'https://openlayers.org/en/latest/examples/geojson.html',
  },
  {
    title: 'Display geometry from a geojson file',
    description: 'Example of using aol-source-geojson',
    routerLink: 'display-geojson-source',
    openLayersLink: 'https://openlayers.org/en/latest/examples/vector-layer.html',
  },
  {
    title: 'Draw Features',
    description: 'Example of using aol-interaction-draw',
    routerLink: 'draw-features',
    openLayersLink: 'https://openlayers.org/en/latest/examples/draw-features.html',
  },
  {
    title: 'Modify polygon',
    description: 'Example of using aol-interaction-modify',
    routerLink: 'modify-polygon',
    openLayersLink: 'https://openlayers.org/en/latest/examples/modify-features.html',
  },
  {
    title: 'Side by side',
    description: 'Compare 2 maps side by side',
    routerLink: 'side-by-side',
    openLayersLink: 'https://openlayers.org/en/latest/examples/side-by-side.html',
  },
  {
    title: 'Swipe',
    description: 'Compare 2 layers tile with swipe',
    routerLink: 'swipe',
    openLayersLink: 'https://openlayers.org/en/latest/examples/layer-swipe.html',
  },
  {
    title: 'Overlay',
    description: 'Example of using aol-overlay',
    routerLink: 'overlay',
    openLayersLink: 'https://openlayers.org/en/latest/examples/overlay.html',
  },
  {
    title: 'Change color when feature is selected or hovered',
    description: 'Change aol-style on hover or on select',
    routerLink: 'color-select-hover',
    openLayersLink: 'https://openlayers.org/en/latest/examples/vector-layer.html',
  },
  {
    title: 'Marker',
    description: 'Display marker with svg on specific point',
    routerLink: 'marker',
    openLayersLink: 'https://openlayers.org/en/latest/examples/icon-color.html',
  },
  {
    title: 'Cluster',
    description: 'Example of using aol-source-cluster. This example shows how to do clustering on point features.',
    routerLink: 'cluster',
    openLayersLink: 'https://openlayers.org/en/latest/examples/cluster.html',
  },
  {
    title: 'Raster',
    description:
      'Example of using raster to perform pixel-based operations. Adjust brightness and contrast in this case.',
    routerLink: 'raster',
    openLayersLink: 'https://openlayers.org/en/latest/examples/raster.html',
  },
  {
    title: 'Image ArcGIS',
    description:
      'Example of using aol-source-imagearcgisrest. This example display exported image of MapServer ArcGis endpoint.',
    routerLink: 'arcgis-image',
    openLayersLink: 'https://openlayers.org/en/latest/examples/arcgis-image.html',
  },
  {
    title: 'Image Load Events',
    description: 'Example of using aol-source-imagewms. This example listens to image loading events.',
    routerLink: 'image-wms',
    openLayersLink: 'https://openlayers.org/en/latest/examples/image-load-events.html',
  },
  {
    title: 'View projection update',
    description: 'Dynamically update view projection.',
    routerLink: 'view-projection-update',
    openLayersLink: 'https://openlayers.org/en/latest/examples/projection-and-scale.html',
  },
  {
    title: 'Overview',
    description: 'Overview of map',
    routerLink: 'overview',
    openLayersLink: 'https://openlayers.org/en/latest/examples/overviewmap.html',
  },
  {
    title: 'UTF Grid',
    description: 'Example of using aol-source-utfgrid. This example display country flag in an overlay on hover',
    routerLink: 'utf-grid',
    openLayersLink: 'https://openlayers.org/en/latest/examples/utfgrid.html',
  },
  {
    title: 'Image static',
    description: 'Example of using aol-source-imagestatic.',
    routerLink: 'image-static',
    openLayersLink: 'https://openlayers.org/en/latest/examples/static-image.html',
  },
  {
    title: 'Select interaction static',
    description: 'Example of using select interaction',
    routerLink: 'select-interaction',
    openLayersLink: 'https://openlayers.org/en/latest/examples/select-features.html',
  },
  {
    title: 'Tile Json',
    description: 'Example of using aol-source-tilejson. This example display mapbox json',
    routerLink: 'tile-json',
    openLayersLink: 'https://openlayers.org/en/latest/examples/tilejson.html',
  },
  {
    title: 'Graticule',
    description: 'Example of using aol-graticule. This example shows how to add a graticule overlay to a map',
    routerLink: 'graticule',
    openLayersLink: 'https://openlayers.org/en/latest/examples/graticule.html',
  },
  {
    title: 'Snap',
    description: 'Example of snap interaction',
    routerLink: 'snap',
    openLayersLink: 'https://openlayers.org/en/latest/examples/snap.html',
  },
  {
    title: 'Style composition',
    description: 'Example of styles composition',
    routerLink: 'styles',
    openLayersLink: 'https://openlayers.org/en/latest/examples/polygon-styles.html',
  },
];
